pipeline{
   agent any 
   tools{
    maven "M2_HOME"
   }
   stages{
    stage('sonar-scan'){
        steps{
            withSonarQubeEnv('sonarQube'){
           sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=marionsaurelle_geo'
            }
         
        }
    }
      
    stage("maven"){
        steps{ 
        sh 'mvn clean '
        sh 'mvn validate'
        sh 'mvn compile' 
        sh 'mvn install' 
        sh 'mvn test'
        sh 'mvn package'
        }
    }
    stage('upload artifact'){
        steps{
        sh 'curl -uadmin:AP2M4cAV2LdZbQyLZfXHmJZLYBm -T \
        target/bio*.jar \
        "http://3.80.150.112:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
        }
    }
    stage('docker login'){
        steps{
            sh 'aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin \
            082438639781.dkr.ecr.us-east-1.amazonaws.com'
        }
    }
      stage('docker image build'){
        steps{
            sh 'docker build -t dev:v.${BUILD_ID} .'    
        }  
    }                                                             
    stage('Image tagging'){
        steps{
             sh 'docker tag dev:latest \
             082438639781.dkr.ecr.us-east-1.amazonaws.com/dev:latest'
             sh 'docker tag dev:latest \
             082438639781.dkr.ecr.us-east-1.amazonaws.com/dev:v.${BUILD_ID}'
        }
    }
        stage('push image'){
            steps{
            sh 'docker push 082438639781.dkr.ecr.us-east-1.amazonaws.com/dev:latest'
            sh 'docker push 082438639781.dkr.ecr.us-east-1.amazonaws.com/dev:v.${BUILD_ID}'
        }
    }
}
}
  