pipeline{
   agent any 
   tools{
    maven "M2_HOME"
   }
   stages{
    stage('sonar-scan'){
        steps{
          sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=marionsaurelle_geo'
        }
    }
      
    stage("maven"){
        steps{ 
        sh 'mvn clean '
        sh 'mvn validate'
        sh 'mvn compile' 
        sh 'mvn install' 
        sh 'mvn test'
        sh 'mvn package'
        }
    }
    stage('upload artifact'){
        steps{
        sh 'curl -uadmin:AP2M4cAV2LdZbQyLZfXHmJZLYBm -T \
        target/bio*.jar \
        "http://ec2-3-83-42-232.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
        }
    }
   }
}